# IBM DBB zAppBuild — application.properties
# Enterprise reference (JPMorgan/Mastercard/US Bank pattern)

build.work.dir=build
dbb.groovy.path=dbb
dbb.groovy.verbose=false

# HLQ for z/OS datasets
hlq=Z77140
cobol.hlq=Z77140.CBL
copybook.hlq=Z77140.COPYBOOK
jcl.hlq=Z77140.JCL
load.hlq=Z77140.LOAD
dbrm.hlq=Z77140.DBRM
rexx.hlq=Z77140.REXX

# Compiler options
cobol.compiler=IYC
cobol.target=cobol

# DB2 subsystem
db2.subsystem=DBCG
db2.plan=CLMPLAN
db2.package=Z77140
