# IBM DBB — Cobol.properties
# Enterprise COBOL compiler options

cobol.compiler=IYC
cobol.datacom=true
cobol.flagIndicator=*
cobol.processtype=preprocess
cobol.db2Preprocessor=DSNHASM

# Standard compile flags
cobol.debug=false
cobol.optimize=2
cobol.threadsafe=true
