-- ==============================================================
-- CLAIMS_MASTER DDL - Insurance Claims Batch System
-- Schema: Z77140
-- Database: CLMSDB    Tablespace: CLMSTS
-- Claim Types: MD=Medical DN=Dental DS=Disability LF=Life
-- ==============================================================

-- Create database (if not exists, run by DBA)
CREATE DATABASE CLMSDB
    STOGROUP SYSDEFLT
    BUFFERPOOL BP0;

-- Create tablespace
CREATE TABLESPACE CLMSTS
    IN CLMSDB
    USING STOGROUP SYSDEFLT
    PRIQTY 720
    SECQTY 720
    SEGSIZE 64
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CLOSE NO
    COMPRESS YES;

-- Create table
CREATE TABLE Z77140.CLAIMS_MASTER (
    POLICY_NO      CHAR(10)       NOT NULL,
    CLAIM_ID       CHAR(8)        NOT NULL,
    CLAIMANT_NAME  CHAR(30)       NOT NULL,
    CLAIM_DATE     DECIMAL(8,0)   NOT NULL,
    CLAIM_TYPE     CHAR(2)        NOT NULL,
    CLAIM_AMOUNT   DECIMAL(9,2)   NOT NULL,
    COVERAGE_CODE  CHAR(3)        NOT NULL,
    STATUS         CHAR(1)        NOT NULL DEFAULT 'V',
    INSERT_TS      TIMESTAMP      NOT NULL WITH DEFAULT,
    CONSTRAINT PK_CLAIMS_MASTER
        PRIMARY KEY (POLICY_NO, CLAIM_ID),
    CONSTRAINT CK_CLM_TYPE
        CHECK (CLAIM_TYPE IN ('MD', 'DN', 'DS', 'LF')),
    CONSTRAINT CK_CLM_STATUS
        CHECK (STATUS IN ('N', 'V', 'R', 'P', 'D')),
    CONSTRAINT CK_CLM_AMOUNT
        CHECK (CLAIM_AMOUNT >= 0)
) IN CLMSDB.CLMSTS;

-- Indexes for query performance
CREATE INDEX Z77140.IDX_CLM_TYPE
    ON Z77140.CLAIMS_MASTER (CLAIM_TYPE ASC)
    USING STOGROUP SYSDEFLT
    PRIQTY 48
    SECQTY 48
    BUFFERPOOL BP0
    CLOSE NO;

CREATE INDEX Z77140.IDX_CLM_DATE
    ON Z77140.CLAIMS_MASTER (CLAIM_DATE DESC)
    USING STOGROUP SYSDEFLT
    PRIQTY 48
    SECQTY 48
    BUFFERPOOL BP0
    CLOSE NO;

CREATE INDEX Z77140.IDX_CLM_AMT
    ON Z77140.CLAIMS_MASTER (CLAIM_AMOUNT DESC)
    USING STOGROUP SYSDEFLT
    PRIQTY 48
    SECQTY 48
    BUFFERPOOL BP0
    CLOSE NO;

-- GRANT access for batch programs
GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE Z77140.CLAIMS_MASTER
    TO PUBLIC;

-- RUNSTATS after initial load (run manually)
-- RUNSTATS TABLESPACE CLMSDB.CLMSTS INDEX(ALL) SHRLEVEL REFERENCE;
