-- Db2 LUW: CLAIMS_MASTER definition for local SQL precompile validation.
-- Production z/OS DDL remains in CLMSDDL.sql. Apply after CREATE SCHEMA Z77140 (see db2-luw-prep-check.sh).

DROP TABLE IF EXISTS Z77140.CLAIMS_MASTER;

CREATE TABLE Z77140.CLAIMS_MASTER (
    POLICY_NO      CHAR(10)       NOT NULL,
    CLAIM_ID       CHAR(8)        NOT NULL,
    CLAIMANT_NAME  CHAR(30)       NOT NULL,
    CLAIM_DATE     DECIMAL(8,0)   NOT NULL,
    CLAIM_TYPE     CHAR(2)        NOT NULL,
    CLAIM_AMOUNT   DECIMAL(9,2)   NOT NULL,
    COVERAGE_CODE  CHAR(3)        NOT NULL,
    STATUS         CHAR(1)        NOT NULL DEFAULT 'V',
    INSERT_TS      TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CLAIMS_MASTER PRIMARY KEY (POLICY_NO, CLAIM_ID),
    CONSTRAINT CK_CLM_TYPE CHECK (CLAIM_TYPE IN ('MD', 'DN', 'DS', 'LF')),
    CONSTRAINT CK_CLM_STATUS CHECK (STATUS IN ('N', 'V', 'R', 'P', 'D')),
    CONSTRAINT CK_CLM_AMOUNT CHECK (CLAIM_AMOUNT >= 0)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Z77140.CLAIMS_MASTER TO PUBLIC;
